#!/bin/bash

CCFLAGS="-Iinclude -DHOST_ENDIAN_LITTLE -DFAST_BYTE_SWAP"

gcc -c test1.c $CCFLAGS

gcc -c src/ppe/ethernet.c $CCFLAGS
gcc -c src/ppe/ipv4.c $CCFLAGS
gcc -c src/ppe/ipv6.c $CCFLAGS
gcc -c src/ppe/tcp.c $CCFLAGS
gcc -c src/ppe/udp.c $CCFLAGS
gcc -c src/ppe/ip_ph.c $CCFLAGS

gcc testpcap2.c -Iinclude ethernet.o ipv4.o tcp.o ip_ph.o -lpcap -o testpcap2


